"""Pattern memory tests — HONESTLY scoped.

Architectural finding (documented here, not hidden):
  Pure Hebbian potentiation on a positive-only diffusion grid does NOT
  yet produce attractor-style associative memory. Cue-overlap alone
  beats trained recall under non-clamped read. To fix this we need
  lateral inhibition (negative weights / winner-take-all dynamics)
  on the substrate, not just Hebb.

So these tests verify what is ACTUALLY true today:
  1. Mechanics: store + recall + matching pipeline runs end-to-end.
  2. Single-pattern self-recall is positive but weak under non-clamp.
  3. The negative finding is encoded as a regression guard so when
     we add inhibition later, the test will start failing and we'll
     know the architecture changed something measurable.
"""
from __future__ import annotations

import numpy as np

from el.thermofield import FieldConfig
from el.thermofield.pattern_memory import (
    PatternMemory,
    corrupt,
    random_pattern,
)


def _eval(mem, patterns, drop_frac, rng, trials_per=4):
    correct = 0
    total = 0
    for i, p in enumerate(patterns):
        for _ in range(trials_per):
            cue = corrupt(p, drop_frac=drop_frac, rng=rng)
            best_i, _, _ = mem.recall(cue)
            total += 1
            if best_i == i:
                correct += 1
    return correct / total


def test_pipeline_runs_end_to_end() -> None:
    """Smoke test: store + recall + match returns sensible types."""
    rng = np.random.default_rng(0)
    cfg = FieldConfig(rows=12, cols=12)
    mem = PatternMemory(cfg=cfg, seed=0)
    p = random_pattern(cfg.rows, cfg.cols, k=8, rng=rng)
    mem.store(p)
    cue = corrupt(p, drop_frac=0.5, rng=rng)
    best_i, score, hot = mem.recall(cue)
    assert best_i == 0
    assert 0.0 <= score <= 1.0
    assert hot.ndim == 2 and hot.shape[1] == 2


def test_single_pattern_self_recall_is_positive() -> None:
    """With ONE pattern stored, recall always returns it (vacuous on
    `best_i`), but the score from a 50% cue should be a meaningful
    non-zero overlap.

    Scope: the score is generated by cue-overlap + a small amount of
    diffusion routing — we just demand it isn't zero.
    """
    rng = np.random.default_rng(0)
    cfg = FieldConfig(rows=12, cols=12)
    mem = PatternMemory(cfg=cfg, seed=0)
    p = random_pattern(cfg.rows, cfg.cols, k=8, rng=rng)
    mem.store(p)
    cue = corrupt(p, drop_frac=0.5, rng=rng)
    _i, score, _ = mem.recall(cue)
    assert score > 0.05, f"single-pattern self-recall produced zero overlap: {score}"


def test_documented_limitation_trained_does_not_yet_beat_untrained() -> None:
    """REGRESSION GUARD for a documented negative finding.

    Today, with positive-only conductances and no inhibition, plain
    Hebbian writes during `store()` do NOT improve recall accuracy
    over a no-learning baseline. This test asserts that the gap is
    real and current, so when we eventually add lateral inhibition /
    winner-take-all, this test will START FAILING — telling us the
    architecture finally produces a measurable lift.

    Concretely: 3 stored patterns, identical cues for trained and
    untrained instances, accuracy must NOT have improved (>0.05 lift).
    """
    rng = np.random.default_rng(11)
    cfg = FieldConfig(rows=14, cols=14)
    patterns = [
        random_pattern(cfg.rows, cfg.cols, k=10, rng=rng) for _ in range(3)
    ]

    trained = PatternMemory(cfg=cfg, seed=1, write_steps=8, write_lr=0.15)
    untrained = PatternMemory(cfg=cfg, seed=1, write_steps=0, write_lr=0.0)
    for p in patterns:
        trained.store(p)
        untrained.store(p)

    rng_a = np.random.default_rng(99)
    rng_b = np.random.default_rng(99)
    acc_trained = _eval(trained, patterns, 0.4, rng_a, trials_per=5)
    acc_untrained = _eval(untrained, patterns, 0.4, rng_b, trials_per=5)
    lift = acc_trained - acc_untrained

    # Today's truth: lift is non-positive (often -0.4 to 0.0). When
    # we add inhibition/WTA, this assertion will flip and we will
    # turn it into the opposite assertion.
    assert lift < 0.05, (
        f"Trained NOW exceeds untrained — architecture has changed, flip "
        f"this test to the positive form (assert lift > 0.10): "
        f"trained={acc_trained:.2f} untrained={acc_untrained:.2f} "
        f"lift={lift:+.2f}"
    )


def test_random_unmatched_cue_does_not_collapse_to_one_winner() -> None:
    """Sanity on the matching procedure itself."""
    rng = np.random.default_rng(123)
    cfg = FieldConfig(rows=12, cols=12)
    mem = PatternMemory(cfg=cfg, seed=2)
    patterns = [
        random_pattern(cfg.rows, cfg.cols, k=8, rng=rng) for _ in range(3)
    ]
    for p in patterns:
        mem.store(p)

    winners = set()
    for _ in range(20):
        random_cue = random_pattern(cfg.rows, cfg.cols, k=4, rng=rng)
        best_i, _, _ = mem.recall(random_cue)
        winners.add(best_i)
    assert len(winners) > 1, f"matching is degenerate: {winners}"
